resource_types:
  - name: cogito
    type: registry-image
    check_every: 1h
    source:
      repository: pix4d/cogito
      tag: latest

  - name: google-chat-resource-type
    check_every: 1h
    type: registry-image
    source:
      repository: cloudinn/concourse-hangouts-resource

resources:
  - name: gh-status
    type: cogito
    icon: comment-alert
    check_every: 1h
    source:
      owner: pix4d
      repo: dependabot-core
      access_token: ((github_repo_status_token))

  - name: google-chat
    type: google-chat-resource-type
    icon: chat-alert
    source:
      webhook_url: ((gchat_hook))
      post_url: true

  - name: dependabot-core.git
    type: git
    icon: git
    source:
      uri: git@github.com:Pix4D/dependabot-core.git
      private_key: ((concourse_janus_ssh_key))
      branch: ((branch))

  - name: upstream-dependabot-core.git
    type: git
    icon: git
    source:
      uri: https://github.com/dependabot/dependabot-core.git
      branch: main
      tag_filter: v*

  - name: pix4d_build_tools.git
    type: git
    icon: git
    source:
      uri: git@github.com:Pix4D/pix4d_build_tools.git
      private_key: ((concourse_janus_ssh_key))
      branch: master

  - name: known-hosts.s3
    type: s3
    source:
      versioned_file: known_hosts
      bucket: ci-pix4d-internal-static
      region_name: eu-west-1
      access_key_id: ((concourse_user_access_key))
      secret_access_key: ((concourse_user_secret_key))

  - name: pix4d-dependabot.docker
    type: registry-image
    source:
      username: ((docker_cloud_pix4d_user))
      password: ((docker_cloud_pix4d_password))
      repository: docker.ci.pix4d.com/pix4d-dependabot
      tag: ((docker_tag))

jobs:
  - name: test-dependabot
    on_success:
      put: gh-status
      inputs: [dependabot-core.git]
      params: {state: success}
    on_error:
      do:
      - put: gh-status
        inputs: [dependabot-core.git]
        params: {state: error}
      - put: google-chat
        inputs: []
        params: {message: Oops! The pipeline encountered an error.}
    on_failure:
      do:
      - put: gh-status
        inputs: [dependabot-core.git]
        params: {state: failure}
      - put: google-chat
        inputs: []
        params: {message: Oops! The pipeline encountered an error.}
    plan:
    - get: dependabot-core.git
      trigger: ((trigger))
    - put: gh-status
      inputs: [dependabot-core.git]
      params: {state: pending}
    - task: build-and-test-dependabot-image
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
        inputs:
        - name: dependabot-core.git
        outputs:
        - name: image
        run:
          path: build
      params:
        CONTEXT: dependabot-core.git/
        DOCKERFILE: dependabot-core.git/Dockerfile.pix4d
    - task: timestamp
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: alpine
        inputs:
        - name: image
        outputs:
        - name: version
        run:
          path: ash
          args:
          - -c
          - |
            set -e
            VERSION=$(date --utc +"%Y%m%d%H%M%S")
            echo "$VERSION bootstrapme" > version/date.txt
    - put: pix4d-dependabot.docker
      inputs: [image, version]
      params:
        image: image/image.tar
        additional_tags: ((docker_tag_add_file))
    - task: pr-auto-merge
      file: dependabot-core.git/ci/tasks/pr-auto-merge.yml

  - name: merge-upstream
    disable_manual_trigger: ((disable_on_feature))
    on_error:
      do:
      - put: google-chat
        inputs: []
        params: {message: Oops! The pipeline encountered an error.}
    on_failure:
      do:
      - put: google-chat
        inputs: []
        params: {message: Oops! The pipeline encountered an error.}
    plan:
    - get: dependabot-core.git
    - get: pix4d_build_tools.git
    - get: known-hosts.s3
    - get: upstream-dependabot-core.git
      trigger: ((trigger))
    - task: check-upstream-status
      file: dependabot-core.git/ci/tasks/check-upstream-status-task.yml
    - task: merge-upstream
      file: dependabot-core.git/ci/tasks/merge-upstream-task.yml
