platform: linux
image_resource:
  type: registry-image
  source:
    repository: ruby
    tag: 2.7-alpine
params:
  REPOSITORY_ACCESS_TOKEN: ((janus_developers_rw_token))

inputs:
- name: dependabot-core.git

run:
  path: /bin/sh
  args:
  - -c
  - |
      set -ex
      gem install octokit -v 4.21.0

      cd dependabot-core.git
      export COMMIT_HASH=$(cat .git/ref)
      ruby ci/tasks/pr_auto_merge.rb
