version: 2
jobs:
  build_and_test_reorg:
    docker:
      # Any image that includes the docker client will do
      - image: circleci/ruby
    steps:
      - run: env

workflows:
  version: 2
  test:
    jobs:
      - build_and_test_reorg
