name: pub_helpers
description: A command-line helper application for the dependabot Dart pub package manger.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'


dev_dependencies:
  pedantic: ^1.9.0
dependencies: 
  args: ^2.0.0
  pub_semver: ^2.0.0
