name: pub_helpers
description: A command-line helper application for the dependabot Dart pub package manger.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'


dev_dependencies:
  pedantic: ^1.9.0
dependencies:
  args: ^2.0.0
  deep_pick: ^0.8.0
  pub_semver: ^2.0.0
  yaml_edit:
    git:
      url: https://github.com/simpleclub-extended/dart-neats.git
      ref: null-safety
      path: yaml_edit

dependency_overrides:
  pub_semver:
    git:
      url: https://github.com/simpleclub-extended/pub_semver.git
      ref: upgrade-constraints
