version: 1
update_configs:
  # Update your Gemfile (& lockfiles) as soon as
  # new versions are published to the RubyGems registry
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"

    # Apply default reviewer and label to created
    # pull requests
    default_reviewers:
      - "github-username"
    default_labels:
      - "label-name"

  - package_manager: "php:composer"
    directory: "/composer/helpers"
    update_schedule: "live"

  - package_manager: "elixir:hex"
    directory: "/hex/helpers"
    update_schedule: "live"

  - package_manager: "javascript"
    directory: "/npm_and_yarn/helpers"
    update_schedule: "live"

  - package_manager: "python"
    directory: "/python/helpers"
    update_schedule: "live"

  - package_manager: "go:modules"
    directory: "/go_modules/helpers"
    update_schedule: "daily"
