name: CI common
on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - Dockerfile
      - 'common/**'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - { path: common, name: common }
    steps:
      - run: echo skipped
