name: CI GitHub Actions
on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - Dockerfile
      - 'common/**'
      - 'github_actions/**'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - { path: github_actions, name: github_actions }
    steps:
      - run: echo skipped
