name: CI Git submodules
on:
  push:
    branches:
      - "main"
    paths:
      - Dockerfile
      - 'common/**'
      - 'git_submodules/**'
  pull_request:
    branches:
      - "main"
    paths:
      - Dockerfile
      - 'common/**'
      - 'git_submodules/**'
  schedule:
    - cron: "0 0 * * *"

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      name: ${{ matrix.suite.name }}
      path: ${{ matrix.suite.path }}
    strategy:
      fail-fast: false
      matrix:
        suite:
          - { path: git_submodules, name: git_submodules }
