name: CI NPM and Yarn
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      name: ${{ matrix.suite.name }}
      path: ${{ matrix.suite.path }}
      ci_node_total: ${{ matrix.suite.ci_node_total }}
      ci_node_index: ${{ matrix.suite.ci_node_index }}
    strategy:
      fail-fast: false
      matrix:
        suite:
          - { path: npm_and_yarn, name: npm_and_yarn, ci_node_total: 3, ci_node_index: 0 }
          - { path: npm_and_yarn, name: npm_and_yarn, ci_node_total: 3, ci_node_index: 1 }
          - { path: npm_and_yarn, name: npm_and_yarn, ci_node_total: 3, ci_node_index: 2 }
