name: CI Nuget
on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - Dockerfile
      - 'common/**'
      - 'nuget/**'
  schedule:
    - cron: "0 0 * * *"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - { path: nuget, name: nuget }
    steps:
      - run: echo skipped
