name: CI Pub
on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - Dockerfile
      - 'common/**'
      - 'pub/**'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - { path: pub, name: pub, ci_node_total: 2, ci_node_index: 0 }
          - { path: pub, name: pub, ci_node_total: 2, ci_node_index: 1 }
    steps:
      - run: echo skipped
