name: CI
on:
  push:
    branches:
      - wip*
      - main
  pull_request_target:
    branches:
      - "**"
jobs:
  ci-image:
    name: Build CI image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare environment variables
        run: |
          echo ::set-env name=VERSION::$(grep -Eo "[0-9]+\.[0-9]+\.[0-9]+" common/lib/dependabot/version.rb)
      - name: Build dependabot-core image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: "dependabot/dependabot-core"
          push_image_and_stages: false
      - name: Remove .dockerignore for dependabot-core-ci image build
        run: rm .dockerignore
      - name: Build dependabot-core-ci image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: x
          password: "${{ secrets.GITHUB_TOKEN }}"
          image_name: "${{ github.repository }}/dependabot-core-ci"
          image_tag: "${{ github.sha }},latest"
          registry: docker.pkg.github.com
          dockerfile: Dockerfile.ci

  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    needs: ci-image
    strategy:
      matrix:
        suite:
          - bundler
          - cargo
          - common
          - composer
          - dep
          - docker
          - elm
          - git_submodules
          - github_actions
          - go_modules
          - gradle
          - hex
          - maven
          - npm_and_yarn
          - nuget
          - omnibus
          - python
          - terraform
    steps:
      - name: Pull image from packages
        run: |
          docker login docker.pkg.github.com -u x -p ${{ secrets.GITHUB_TOKEN }}
          docker pull "docker.pkg.github.com/${{ github.repository }}/dependabot-core-ci:${{ github.sha }}"
      - name: Run Rubocop linting
        run: |
          docker run --rm docker.pkg.github.com/${{ github.repository }}/dependabot-core-ci:${{ github.sha }} bash -c "cd /home/dependabot/dependabot-core/${{ matrix.suite }} && bundle exec rubocop . -c ../.rubocop.yml"

  rspec:
    name: Rspec
    runs-on: ubuntu-latest
    needs: ci-image
    strategy:
      matrix:
        suite:
          - bundler
          - cargo
          - common
          - composer
          - dep
          - docker
          - elm
          - git_submodules
          - github_actions
          - go_modules
          - gradle
          - hex
          - maven
          - npm_and_yarn
          - nuget
          - omnibus
          - python
          - terraform

    steps:
      - name: Pull image from packages
        run: |
          docker login docker.pkg.github.com -u x -p ${{ secrets.GITHUB_TOKEN }}
          docker pull "docker.pkg.github.com/${{ github.repository }}/dependabot-core-ci:${{ github.sha }}"
      - name: Run ${{ matrix.suite }} tests with rspec
        run: |
          docker run --rm docker.pkg.github.com/${{ github.repository }}/dependabot-core-ci:${{ github.sha }} bash -c "cd /home/dependabot/dependabot-core/${{ matrix.suite }} && bundle exec rspec spec"

  npm-and-yarn-js:
    name: npm and yarn js
    runs-on: ubuntu-latest
    needs: ci-image
    steps:
      - name: Pull image from packages
        run: |
          docker login docker.pkg.github.com -u x -p ${{ secrets.GITHUB_TOKEN }}
          docker pull "docker.pkg.github.com/${{ github.repository }}/dependabot-core-ci:${{ github.sha }}"
      - name: Run js linting
        run: |
           docker run --rm docker.pkg.github.com/${{ github.repository }}/dependabot-core-ci:${{ github.sha }} bash -c "cd /opt/npm_and_yarn && yarn lint"
      - name: Run js tests
        run: |
           docker run --rm docker.pkg.github.com/${{ github.repository }}/dependabot-core-ci:${{ github.sha }} bash -c "cd /opt/npm_and_yarn && yarn test"
