name: CI
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      path:
        required: true
        type: string
      ci_node_total:
        required: false
        type: number
      ci_node_index:
        required: false
        type: number

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build dependabot-core image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            -t "dependabot/dependabot-core:latest" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ghcr.io/dependabot/dependabot-core \
            .
      - name: Build dependabot-core-ci image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            -f Dockerfile.ci \
            -t "dependabot-core-ci:latest" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            .
      - name: Run ${{ inputs.name }} tests
        run: |
          docker run \
            --env "CI=true" \
            --env "RAISE_ON_WARNINGS=true" \
            --env "DEPENDABOT_TEST_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}" \
            --env "SUITE_NAME=${{ inputs.name }}" \
            --env "CI_NODE_TOTAL=${{ inputs.ci_node_total }}" \
            --env "CI_NODE_INDEX=${{ inputs.ci_node_index }}" \
            --rm dependabot-core-ci bash -c \
            "cd /home/dependabot/dependabot-core/${{ inputs.path }} && ./script/ci-test"
