name: CI
on:
  - pull_request
  - push

jobs:
  ci-image:
    name: Build CI image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare environment variables
        run: |
          echo ::set-env name=VERSION::$(grep -Eo "[0-9]+\.[0-9]+\.[0-9]+" common/lib/dependabot/version.rb)
      - name: Pull Docker base images & warm Docker cache
        run: |
          docker pull ubuntu:18.04
          docker pull "dependabot/dependabot-core:latest"
          docker pull "dependabot/dependabot-core-ci:latest" || true
      - name: Build dependabot-core-ci image
        run: |
          rm .dockerignore
          docker build \
            -t "dependabot/dependabot-core-ci:${{ github.sha }}" \
            -f Dockerfile.ci \
            --cache-from ubuntu:18.04 \
            --cache-from "dependabot/dependabot-core:latest" \
            --cache-from "dependabot/dependabot-core-ci:latest" \
            .
          docker image save -o dependabot-core-ci-image.tar "dependabot/dependabot-core-ci:${{ github.sha }}"
      - name: Save image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dependabot-core-ci-image.tar
          path: dependabot-core-ci-image.tar

  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    needs: ci-image
    steps:
      - name: Load docker image from artifacts
        uses: actions/download-artifact@v2
        with:
          name: dependabot-core-ci-image.tar
      - name: Restore image
        run: |
          cat dependabot-core-ci-image.tar | docker import - dependabot/dependabot-core-ci:${{ github.sha }}
      - name: Run Rubocop linting
        run: |
          docker run --rm dependabot/dependabot-core:${{ github.sha }} bash -c "cd /home/dependabot/dependabot-core && rake ci:rubocop"

  rspec:
    name: Rspec
    runs-on: ubuntu-latest
    container: dependabot/dependabot-core-ci:${{ github.sha }}
    needs: ci-image
    strategy:
      matrix:
        suite:
          - bundler
          - cargo
          - common
          - composer
          - dep
          - docker
          - elm
          - git_submodules
          - go_modules
          - gradle
          - hex
          - maven
          - npm_and_yarn
          - nuget
          - omnibus
          - python
          - terraform

    steps:
      - name: Load docker image from artifacts
        uses: actions/download-artifact@v2
        with:
          name: dependabot-core-ci-image.tar
      - name: Restore image
        run: |
          cat dependabot-core-ci-image.tar | docker import - dependabot/dependabot-core-ci:${{ github.sha }}
      - name: Run ${{ matrix.suite }} tests with rspec
        run: |
          docker run --rm dependabot/dependabot-core:${{ github.sha }} bash -c "cd /home/dependabot/${{ matrix.suite }} && rake ci:rubocop"


  npm-and-yarn-js:
    name: npm and yarn js
    runs-on: ubuntu-latest
    needs: ci-image
    steps:
      - name: Load docker image from artifacts
        uses: actions/download-artifact@v2
        with:
          name: dependabot-core-ci-image.tar
      - name: Restore image
        run: |
          cat dependabot-core-ci-image.tar | docker import - dependabot/dependabot-core-ci:${{ github.sha }}
      - name: Run js linting
        run: |
           docker run --rm dependabot/dependabot-core:${{ github.sha }} bash -c "cd /opt/npm_and_yarn && yarn lint"
      - name: Run js tests
        run: |
           docker run --rm dependabot/dependabot-core:${{ github.sha }} bash -c "cd /opt/npm_and_yarn && yarn test"
