name: Push docker images

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  push-core-image:
    name: Push dependabot-core image to docker hub
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'dependabot/dependabot-core' }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Log in to the Docker registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Docker tags
        id: tags
        uses: docker/metadata-action@v4
        with:
          images: |
            dependabot/dependabot-core
            ghcr.io/dependabot/dependabot-core
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
      - name: Build and push ${{ matrix.arch }} dependabot-core image
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          platforms: linux/${{ matrix.arch }}
          cache-from: type=registry,ref=dependabot/dependabot-core:latest
          cache-to: type=inline
          tags: ${{ steps.tags.outputs.tags }}

  push-development-image:
    name: Push dependabot-core-development image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: push-core-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Docker tags
        id: tags
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/dependabot/dependabot-core-development
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
      - name: Build and push ${{ matrix.arch }} dependabot-core-development image
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          file: Dockerfile.development
          platforms: linux/${{ matrix.arch }}
          cache-from: type=registry,ref=ghcr.io/dependabot/dependabot-core-development:latest
          cache-to: type=inline
          tags: ${{ steps.tags.outputs.tags }}
